/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedDataRouteImport } from './routes/_authenticated/data'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedScrapersRouteImport } from './routes/_authenticated/scrapers'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated/status'
import { Route as AuthenticatedFixIdRouteImport } from './routes/_authenticated/fix.$id'
import { Route as OauthGoogleSheetsReturnRouteImport } from './routes/oauth/google-sheets/return'
import { Route as ApiPublicTriageIngestRouteImport } from './routes/api/public/triage/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataRoute = AuthenticatedDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScrapersRoute = AuthenticatedScrapersRouteImport.update({
  id: '/scrapers',
  path: '/scrapers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFixIdRoute = AuthenticatedFixIdRouteImport.update({
  id: '/fix/$id',
  path: '/fix/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OauthGoogleSheetsReturnRoute = OauthGoogleSheetsReturnRouteImport.update({
  id: '/oauth/google-sheets/return',
  path: '/oauth/google-sheets/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTriageIngestRoute = ApiPublicTriageIngestRouteImport.update({
  id: '/api/public/triage/ingest',
  path: '/api/public/triage/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/data': typeof AuthenticatedDataRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/scrapers': typeof AuthenticatedScrapersRoute
  '/status': typeof AuthenticatedStatusRoute
  '/fix/$id': typeof AuthenticatedFixIdRoute
  '/oauth/google-sheets/return': typeof OauthGoogleSheetsReturnRoute
  '/api/public/triage/ingest': typeof ApiPublicTriageIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/data': typeof AuthenticatedDataRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/scrapers': typeof AuthenticatedScrapersRoute
  '/status': typeof AuthenticatedStatusRoute
  '/fix/$id': typeof AuthenticatedFixIdRoute
  '/oauth/google-sheets/return': typeof OauthGoogleSheetsReturnRoute
  '/api/public/triage/ingest': typeof ApiPublicTriageIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/data': typeof AuthenticatedDataRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/scrapers': typeof AuthenticatedScrapersRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/fix/$id': typeof AuthenticatedFixIdRoute
  '/oauth/google-sheets/return': typeof OauthGoogleSheetsReturnRoute
  '/api/public/triage/ingest': typeof ApiPublicTriageIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/builder'
    | '/connect'
    | '/data'
    | '/history'
    | '/queue'
    | '/scrapers'
    | '/status'
    | '/fix/$id'
    | '/oauth/google-sheets/return'
    | '/api/public/triage/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/builder'
    | '/connect'
    | '/data'
    | '/history'
    | '/queue'
    | '/scrapers'
    | '/status'
    | '/fix/$id'
    | '/oauth/google-sheets/return'
    | '/api/public/triage/ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/builder'
    | '/_authenticated/connect'
    | '/_authenticated/data'
    | '/_authenticated/history'
    | '/_authenticated/queue'
    | '/_authenticated/scrapers'
    | '/_authenticated/status'
    | '/_authenticated/fix/$id'
    | '/oauth/google-sheets/return'
    | '/api/public/triage/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OauthGoogleSheetsReturnRoute: typeof OauthGoogleSheetsReturnRoute
  ApiPublicTriageIngestRoute: typeof ApiPublicTriageIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data': {
      id: '/_authenticated/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthenticatedDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scrapers': {
      id: '/_authenticated/scrapers'
      path: '/scrapers'
      fullPath: '/scrapers'
      preLoaderRoute: typeof AuthenticatedScrapersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fix/$id': {
      id: '/_authenticated/fix/$id'
      path: '/fix/$id'
      fullPath: '/fix/$id'
      preLoaderRoute: typeof AuthenticatedFixIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/google-sheets/return': {
      id: '/oauth/google-sheets/return'
      path: '/oauth/google-sheets/return'
      fullPath: '/oauth/google-sheets/return'
      preLoaderRoute: typeof OauthGoogleSheetsReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/triage/ingest': {
      id: '/api/public/triage/ingest'
      path: '/api/public/triage/ingest'
      fullPath: '/api/public/triage/ingest'
      preLoaderRoute: typeof ApiPublicTriageIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRoute
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedDataRoute: typeof AuthenticatedDataRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedScrapersRoute: typeof AuthenticatedScrapersRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
  AuthenticatedFixIdRoute: typeof AuthenticatedFixIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuilderRoute: AuthenticatedBuilderRoute,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedDataRoute: AuthenticatedDataRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedScrapersRoute: AuthenticatedScrapersRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
  AuthenticatedFixIdRoute: AuthenticatedFixIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OauthGoogleSheetsReturnRoute: OauthGoogleSheetsReturnRoute,
  ApiPublicTriageIngestRoute: ApiPublicTriageIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
